language: node_js

notifications:
  slack: generaptr:WVInkDTeAegbpm2wBcMmCKv2
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a80c735c20f7603bf06a
    on_success: change  
    on_failure: always  
    on_start: never     

node_js:
  - "7.5"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test;'
  - mysql -u root test < ./test/tracks/mysql/data.sql

script:
  - npm run test:coverages

after_success:
  - npm run coveralls
